- name: Upgrade all packages
  apt:
    name: '*'
    state: latest

- name: Install git
  apt:
    name: git
    state: present
    update_cache: yes

- name: Install wget
  apt:
    name: wget
    state: present

- name: Install curl
  yum:
    name: curl
    state: present

- name: Install htop
  apt:
    name: htop
    state: present

- name: Install mc
  apt:
    name: mc
    state: present

- name:
  apt:
    name: net-tools
    state: present

- name: Add ansible repository.
  apt_repository: repo='ppa:ansible/ansible'

- name: Update apt cache.
  apt: update_cache=true cache_valid_time=86400

- name: Install Ansible.
  apt:
    name: ansible
    state: present